steps:
- name: 'gcr.io/flutter-website-1337/flutterwebsite-image'
  args: ['build', '-t', 'gcr.io/flutter-website-1337/flutterwebsite-image:latest', '.']
- name: 'gcr.io/flutter-website-1337/flutterwebsite-image'
  args: ['push', 'gcr.io/flutter-website-1337/flutterwebsite-image:latest']
- name: 'gcr.io/flutter-website-1337/gcloud'
  args: ['beta', 'run', 'deploy', 'flutterwebsite-cloudrun', '--image=gcr.io/flutter-website-1337/flutterwebsite-image:latest', '--region=us-east4']